# Generated by Django 3.0.8 on 2020-10-16 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('desc', models.CharField(default='NA', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DL_No', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=70)),
                ('dateOfIssue', models.DateTimeField()),
                ('validTill', models.DateTimeField()),
                ('picture', models.ImageField(upload_to='ProfilesPics')),
                ('RTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.RTO')),
                ('category', models.ManyToManyField(blank=True, to='scanner.Category')),
                ('state', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scanner.State')),
            ],
        ),
    ]
